version: "1.0"
stages:
  - "clone"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "olegcf/mariadb"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "master"
    git: "Codefresh"
    stage: "clone"
